title: Zhuoao Li's Homepage

page-top-title: Zhuoao Li

top-section-bg-text: Multimodal Learning · Medical AI

home-subtitle: Zhuoao Li | 李卓奥

copyright-text: '© Zhuoao Li 2026. All Rights Reserved.'

sections:
  - id: home
    nav: HOME
    title: Zhuoao Li&ensp;|&ensp;李卓奥
    href: '#page-top'

  - id: publications
    nav: PUBLICATIONS
    title: PUBLICATIONS
    icon: bi-file-text-fill

  - id: awards
    nav: HONORS
    title: HONORS & AWARDSs
    icon: bi-award-fill

backgrounds:
  - static/assets/background/background_0.jpeg

background-interval-ms: 7000
background-overlay: 0.58